OpenCBDC Transaction Processor: client-cli.cpp File Reference
client-cli.cpp File Reference
#include "atomizer_client.hpp"
#include "bech32/bech32.h"
#include "bech32/util/strencodings.h"
#include "client.hpp"
#include "crypto/sha256.h"
#include "twophase_client.hpp"
#include "uhs/transaction/messages.hpp"
#include "util/common/config.hpp"
#include "util/serialization/util.hpp"
#include <future>
#include <iostream>
Functions
auto mint_command (cbdc::client &client, const std::vector< std::string > &args) -> bool
auto decode_address (const std::string &addr_str) -> std::optional< cbdc::hash_t >
void print_tx_result (const std::optional< cbdc::transaction::full_tx > &tx, const std::optional< cbdc::sentinel::execute_response > &resp, const cbdc::hash_t &pubkey)
auto send_command (cbdc::client &client, const std::vector< std::string > &args) -> bool
auto fan_command (cbdc::client &client, const std::vector< std::string > &args) -> bool
void print_pubkey (cbdc::pubkey_t pk)
void newaddress_command (cbdc::client &client)
auto importinput_command (cbdc::client &client, const std::vector< std::string > &args) -> bool
auto confirmtx_command (cbdc::client &client, const std::vector< std::string > &args) -> bool
auto main (int argc, char **argv) -> int
Function Documentation
confirmtx_command()
auto confirmtx_command (cbdc::client & client, const std::vector< std::string > & args) -> bool
Definition at line 198 of file client-cli.cpp.
References cbdc::hash_from_hex(), and cbdc::client::print_amount().
Referenced by main().
decode_address()
auto decode_address (const std::string & addr_str) -> std::optional<cbdc::hash_t>
Definition at line 41 of file client-cli.cpp.
References cbdc::client::public_key.
Referenced by fan_command(), and send_command().
fan_command()
auto fan_command (cbdc::client & client, const std::vector< std::string > & args) -> bool
Definition at line 125 of file client-cli.cpp.
References decode_address(), and print_tx_result().
Referenced by main().
importinput_command()
auto importinput_command (cbdc::client & client, const std::vector< std::string > & args) -> bool
Definition at line 180 of file client-cli.cpp.
References cbdc::buffer::from_hex().
Referenced by main().
main()
auto main (int argc, char ** argv) -> int
Definition at line 213 of file client-cli.cpp.
References confirmtx_command(), fan_command(), cbdc::config::get_args(), importinput_command(), cbdc::config::load_options(), mint_command(), newaddress_command(), cbdc::client::print_amount(), print_pubkey(), and send_command().
mint_command()
auto mint_command (cbdc::client & client, const std::vector< std::string > & args) -> bool
Definition at line 22 of file client-cli.cpp.
References cbdc::to_string(), and cbdc::transaction::tx_id().
Referenced by main().
newaddress_command()
void newaddress_command (cbdc::client & client)
Definition at line 174 of file client-cli.cpp.
References cbdc::client::new_address(), and print_pubkey().
Referenced by main().
print_pubkey()
void print_pubkey (cbdc::pubkey_t pk)
Definition at line 155 of file client-cli.cpp.
References cbdc::client::public_key.
Referenced by main(), and newaddress_command().
print_tx_result()
void print_tx_result (const std::optional< cbdc::transaction::full_tx > & tx, const std::optional< cbdc::sentinel::execute_response > & resp, const cbdc::hash_t & pubkey)
Definition at line 71 of file client-cli.cpp.
References cbdc::client::export_send_inputs(), cbdc::make_buffer(), cbdc::transaction::validation::to_string(), cbdc::to_string(), cbdc::sentinel::to_string(), and cbdc::transaction::tx_id().
Referenced by fan_command(), and send_command().
send_command()
auto send_command (cbdc::client & client, const std::vector< std::string > & args) -> bool
Definition at line 98 of file client-cli.cpp.
References decode_address(), and print_tx_result().
Referenced by main().